import { Injectable } from "@angular/core";

@Injectable({
  providedIn: 'root',
})

export class avatar {
  avatarList: string[] = [
    'alien.png',
    'arbre.png',
    'AvatarF1.png',
    'AvatarF4.png',
    'AvatarF6.png',
    'AvatarF8.png',
    'AvatarF9.png',
    'AvatarF11.png',
    'AvatarF13.png',
    'AvatarF15.png',
    'AvatarH1.png',
    'AvatarH3.png',
    'AvatarH4.png',
    'AvatarH7.png',
    'AvatarH10.png',
    'AvatarH11.png',
    'AvatarH13.png',
    'AvatarH14.png',
    'bff.png',
    'chat-noir.png',
    'chat.png',
    'chevalier.png',
    'chien1.png',
    'chien2.png',
    'dragon.png',
    'hommefuture.png',
    'lapin.png',
    'licorne1.png',
    'licorne2.png',
    'oiseau.png',
    'princesse.png',
    'roi.png',
    'viking.png',
  ];
}
// 'assets/Avatar/alien.png',
//     'assets/Avatar/arbre.png',
//     'assets/Avatar/AvatarF1.png',
//     'assets/Avatar/AvatarF4.png',
//     'assets/Avatar/AvatarF6.png',
//     'assets/Avatar/AvatarF8.png',
//     'assets/Avatar/AvatarF9.png',
//     'assets/Avatar/AvatarF11.png',
//     'assets/Avatar/AvatarF13.png',
//     'assets/Avatar/AvatarF15.png',
//     'assets/Avatar/AvatarH1.png',
//     'assets/Avatar/AvatarH3.png',
//     'assets/Avatar/AvatarH4.png',
//     'assets/Avatar/AvatarH7.png',
//     'assets/Avatar/AvatarH10.png',
//     'assets/Avatar/AvatarH11.png',
//     'assets/Avatar/AvatarH13.png',
//     'assets/Avatar/AvatarH14.png',
//     'assets/Avatar/bff.png',
//     'assets/Avatar/chat-noir.png',
//     'assets/Avatar/chat.png',
//     'assets/Avatar/chevalier.png',
//     'assets/Avatar/chien1.png',
//     'assets/Avatar/chien2.png',
//     'assets/Avatar/dragon.png',
//     'assets/Avatar/hommefuture.png',
//     'assets/Avatar/lapin.png',
//     'assets/Avatar/licorne1.png',
//     'assets/Avatar/licorne2.png',
//     'assets/Avatar/oiseau.png',
//     'assets/Avatar/princesse.png',
//     'assets/Avatar/roi.png',
//     'assets/Avatar/viking.png',
